import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder Firebase configuration. Replace the values with those generated by
/// the FlutterFire CLI for each platform before releasing the app.
class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError('Plataforma no soportada. Configura Firebase primero.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbysipgC7jnKItgGzSULzRGnsPnC5U2Y',
    appId: '1:735814338688:web:f84e88a008ea8aa1a4fe65',
    messagingSenderId: '735814338688',
    projectId: 'upsessions-31987',
    authDomain: 'upsessions-31987.firebaseapp.com',
    storageBucket: 'upsessions-31987.firebasestorage.app',
    measurementId: 'G-DK8CD9TBK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JJ9g72o1aJdyA3Z2OIKNi9HbA5FQzd8',
    appId: '1:735814338688:android:445f7e6a35adbe03a4fe65',
    messagingSenderId: '735814338688',
    projectId: 'upsessions-31987',
    storageBucket: 'upsessions-31987.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-0fWZDQsYYJSHEMFLPWQzAKl-KbOQc5A',
    appId: '1:735814338688:ios:7b48e86a55a6c014a4fe65',
    messagingSenderId: '735814338688',
    projectId: 'upsessions-31987',
    storageBucket: 'upsessions-31987.firebasestorage.app',
    iosBundleId: 'com.example.musicInTouch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: 'REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
    iosBundleId: 'com.example.musicInTouch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WINDOWS_API_KEY',
    appId: 'REPLACE_WITH_WINDOWS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'REPLACE_WITH_LINUX_API_KEY',
    appId: 'REPLACE_WITH_LINUX_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
  );
}