const Map<String, String> _bucketArtistsRaw = {
  'rock': """
The Beatles | 2. Led Zeppelin | 3. Pink Floyd | 4. The Rolling Stones | 5. Queen | 6. Jimi Hendrix | 7. Nirvana | 8. David Bowie | 9. The Doors | 10. AC/DC | 11. Deep Purple | 12. The Who | 13. Black Sabbath | 14. Guns N' Roses | 15. Radiohead | 16. U2 | 17. Aerosmith | 18. Bruce Springsteen | 19. Fleetwood Mac | 20. Metallica | 21. Pearl Jam | 22. Red Hot Chili Peppers | 23. R.E.M. | 24. Dire Straits | 25. The Police | 26. Bon Jovi | 27. Linkin Park | 28. Oasis | 29. Foo Fighters | 30. The Clash | 31. Iron Maiden | 32. Kiss | 33. Van Halen | 34. Rush | 35. Creedence Clearwater Revival | 36. Janis Joplin | 37. Santana | 38. ZZ Top | 39. The Velvet Underground | 40. Scorpions | 41. Genesis | 42. King Crimson | 43. Yes | 44. Jethro Tull | 45. Alice in Chains | 46. Soundgarden | 47. Green Day | 48. Muse | 49. Coldplay | 50. The Kinks | 51. The Beach Boys | 52. Eagles | 53. Journey | 54. Boston | 55. Def Leppard | 56. Mötley Crüe | 57. Whitesnake | 58. Thin Lizzy | 59. Motorhead | 60. Judas Priest | 61. Pantera | 62. Slayer | 63. Megadeth | 64. Rage Against the Machine | 65. Arctic Monkeys | 66. The Strokes | 67. The White Stripes | 68. Queens of the Stone Age | 69. Tool | 70. Nine Inch Nails | 71. Marilyn Manson | 72. Depeche Mode | 73. The Cure | 74. The Smiths | 75. Joy Division | 76. T. Rex | 77. Iggy Pop | 78. Lou Reed | 79. Patti Smith | 80. Blondie | 81. Tom Petty | 82. Neil Young | 83. Bob Dylan | 84. Eric Clapton | 85. Jeff Beck | 86. Stevie Ray Vaughan | 87. Gary Moore | 88. Joe Satriani | 89. Steve Vai | 90. Slash | 91. Eddie Van Halen | 92. Chuck Berry | 93. Little Richard | 94. Jerry Lee Lewis | 95. Elvis Presley | 96. Buddy Holly | 97. Roy Orbison | 98. Lynyrd Skynyrd | 99. The Allman Brothers Band | 100. Toto.
""",
  'pop': """
Michael Jackson | 2. Madonna | 3. The Beatles | 4. Elvis Presley | 5. Prince | 6. Whitney Houston | 7. Mariah Carey | 8. Beyoncé | 9. Taylor Swift | 10. Britney Spears | 11. Elton John | 12. George Michael | 13. ABBA | 14. Lady Gaga | 15. Justin Timberlake | 16. Rihanna | 17. Adele | 18. Bruno Mars | 19. Katy Perry | 20. Justin Bieber | 21. Ariana Grande | 22. Ed Sheeran | 23. Robbie Williams | 24. Celine Dion | 25. Cher | 26. Tina Turner | 27. Donna Summer | 28. Bee Gees | 29. Phil Collins | 30. Billy Joel | 31. Sting | 32. Cyndi Lauper | 33. Janet Jackson | 34. Shakira | 35. Enrique Iglesias | 36. Ricky Martin | 37. Christina Aguilera | 38. Pink | 39. Kelly Clarkson | 40. Gwen Stefani | 41. Avril Lavigne | 42. Backstreet Boys | 43. *NSYNC | 44. Spice Girls | 45. Destiny's Child | 46. Maroon 5 | 47. One Direction | 48. Harry Styles | 49. Dua Lipa | 50. Billie Eilish | 51. Olivia Rodrigo | 52. Miley Cyrus | 53. Demi Lovato | 54. Selena Gomez | 55. The Weeknd | 56. Sam Smith | 57. Shawn Mendes | 58. Sia | 59. Lorde | 60. Lana Del Rey | 61. Norah Jones | 62. Michael Bublé | 63. Barry Manilow | 64. Neil Diamond | 65. Barbra Streisand | 66. Diana Ross | 67. The Supremes | 68. The Jackson 5 | 69. Carpenters | 70. Olivia Newton-John | 71. Kylie Minogue | 72. George Harrison | 73. Paul McCartney | 74. John Lennon | 75. Ringo Starr | 76. Annie Lennox | 77. Eurythmics | 78. Pet Shop Boys | 79. Duran Duran | 80. Culture Club | 81. Wham! | 82. Hall & Oates | 83. Huey Lewis and the News | 84. Rick Astley | 85. Bananarama | 86. Take That | 87. New Kids on the Block | 88. Hanson | 89. Savage Garden | 90. No Doubt | 91. Black Eyed Peas | 92. Pussycat Dolls | 93. Nelly Furtado | 94. Jennifer Lopez | 95. Camila Cabello | 96. Doja Cat | 97. Post Malone | 98. Charlie Puth | 99. Meghan Trainor | 100. Lizzo.
""",
  'indie': """
The Smiths | 2. Pixies | 3. Radiohead | 4. Arctic Monkeys | 5. The Strokes | 6. Arcade Fire | 7. Tame Impala | 8. Joy Division | 9. The Cure | 10. R.E.M. | 11. Sonic Youth | 12. Pavement | 13. Neutral Milk Hotel | 14. My Bloody Valentine | 15. The White Stripes | 16. Interpol | 17. Vampire Weekend | 18. LCD Soundsystem | 19. Bon Iver | 20. Sufjan Stevens | 21. The National | 22. Fleet Foxes | 23. Wilco | 24. Elliott Smith | 25. Modest Mouse | 26. Franz Ferdinand | 27. Bloc Party | 28. The Killers | 29. Florence + The Machine | 30. Lana Del Rey | 31. Beach House | 32. Alt-J | 33. Glass Animals | 34. Mac DeMarco | 35. Mitski | 36. Phoebe Bridgers | 37. Big Thief | 38. The 1975 | 39. Mumford & Sons | 40. Hozier | 41. Kings of Leon | 42. Death Cab for Cutie | 43. Snow Patrol | 44. Keane | 45. The Libertines | 46. Babyshambles | 47. Yeah Yeah Yeahs | 48. TV on the Radio | 49. Animal Collective | 50. Grizzly Bear | 51. Dirty Projectors | 52. St. Vincent | 53. Feist | 54. Cat Power | 55. Fiona Apple | 56. PJ Harvey | 57. Björk | 58. Beck | 59. Sigur Rós | 60. Mogwai | 61. Godspeed You! Black Emperor | 62. Yo La Tengo | 63. Dinosaur Jr. | 64. Guided by Voices | 65. Built to Spill | 66. Spoon | 67. The Shins | 68. Iron & Wine | 69. Bright Eyes | 70. Conor Oberst | 71. Father John Misty | 72. Kurt Vile | 73. Courtney Barnett | 74. IDLES | 75. Fontaines D.C. | 76. Black Midi | 77. Squid | 78. Dry Cleaning | 79. Wet Leg | 80. Wolf Alice | 81. London Grammar | 82. Chvrches | 83. The xx | 84. James Blake | 85. FKA Twigs | 86. Arlo Parks | 87. Japanese Breakfast | 88. Snail Mail | 89. Soccer Mommy | 90. Clairo | 91. Men I Trust | 92. Khruangbin | 93. Unknown Mortal Orchestra | 94. Real Estate | 95. Deerhunter | 96. Car Seat Headrest | 97. Parquet Courts | 98. Sleater-Kinney | 99. Bikini Kill | 100. Fugazi.
""",
  'funkSoulRb': """
James Brown | 2. Aretha Franklin | 3. Stevie Wonder | 4. Marvin Gaye | 5. Prince | 6. Ray Charles | 7. Otis Redding | 8. Michael Jackson | 9. Al Green | 10. Curtis Mayfield | 11. Bill Withers | 12. Sam Cooke | 13. Sly & The Family Stone | 14. George Clinton (Parliament-Funkadelic) | 15. Rick James | 16. Earth, Wind & Fire | 17. The Isley Brothers | 18. The Temptations | 19. The Supremes | 20. Gladys Knight & The Pips | 21. Smokey Robinson | 22. Diana Ross | 23. Whitney Houston | 24. Mary J. Blige | 25. Mariah Carey | 26. Janet Jackson | 27. Beyoncé | 28. Alicia Keys | 29. Usher | 30. R. Kelly | 31. Luther Vandross | 32. Barry White | 33. Isaac Hayes | 34. Chaka Khan | 35. Tina Turner | 36. Patti LaBelle | 37. Roberta Flack | 38. Donny Hathaway | 39. Erykah Badu | 40. Lauryn Hill | 41. D'Angelo | 42. Maxwell | 43. Jill Scott | 44. Sade | 45. Amy Winehouse | 46. Frank Ocean | 47. SZA | 48. H.E.R. | 49. John Legend | 50. Bruno Mars | 51. Anderson .Paak | 52. Childish Gambino | 53. Solange | 54. Janelle Monáe | 55. Kool & The Gang | 56. Commodores | 57. Chic | 58. Nile Rodgers | 59. Gap Band | 60. Ohio Players | 61. Cameo | 62. Zapp & Roger | 63. Bootsy Collins | 64. Maceo Parker | 65. Fred Wesley | 66. Average White Band | 67. Tower of Power | 68. War | 69. Cymande | 70. Betty Davis | 71. Shuggie Otis | 72. Bobby Womack | 73. Solomon Burke | 74. Wilson Pickett | 75. Percy Sledge | 76. Ben E. King | 77. Jackie Wilson | 78. Etta James | 79. Nina Simone | 80. Esther Phillips | 81. Sharon Jones & The Dap-Kings | 82. Charles Bradley | 83. Leon Bridges | 84. Gary Clark Jr. | 85. Thundercat | 86. Flying Lotus | 87. Kali Uchis | 88. Jorja Smith | 89. Snoh Aalegra | 90. Lucky Daye | 91. Giveon | 92. Summer Walker | 93. Jhené Aiko | 94. Kehlani | 95. Teyana Taylor | 96. Ne-Yo | 97. Chris Brown | 98. Trey Songz | 99. Ginuwine | 100. Aaliyah.
""",
  'jazzBlues': """
Miles Davis | 2. Louis Armstrong | 3. John Coltrane | 4. Duke Ellington | 5. Charlie Parker | 6. B.B. King | 7. Robert Johnson | 8. Muddy Waters | 9. Howlin' Wolf | 10. Ella Fitzgerald | 11. Billie Holiday | 12. Nina Simone | 13. Thelonious Monk | 14. Charles Mingus | 15. Herbie Hancock | 16. Chick Corea | 17. Dave Brubeck | 18. Count Basie | 19. Dizzy Gillespie | 20. Chet Baker | 21. Stan Getz | 22. Bill Evans | 23. Oscar Peterson | 24. Wes Montgomery | 25. Django Reinhardt | 26. Sarah Vaughan | 27. Nat King Cole | 28. Frank Sinatra | 29. Ray Charles | 30. Buddy Guy | 31. John Lee Hooker | 32. Albert King | 33. Freddie King | 34. Stevie Ray Vaughan | 35. Eric Clapton | 36. Gary Moore | 37. Joe Bonamassa | 38. Robert Cray | 39. Taj Mahal | 40. Keb' Mo' | 41. Etta James | 42. Bessie Smith | 43. Ma Rainey | 44. Big Mama Thornton | 45. Koko Taylor | 46. Shemekia Copeland | 47. Norah Jones | 48. Diana Krall | 49. Esperanza Spalding | 50. Kamasi Washington | 51. Robert Glasper | 52. Gregory Porter | 53. Jamie Cullum | 54. Michael Bublé | 55. Wynton Marsalis | 56. Branford Marsalis | 57. Wayne Shorter | 58. Sonny Rollins | 59. Ornette Coleman | 60. Sun Ra | 61. Pharoah Sanders | 62. Alice Coltrane | 63. Kamasi Washington | 64. Christian Scott aTunde Adjuah | 65. Makaya McCraven | 66. Yussef Dayes | 67. Nubya Garcia | 68. Shabaka Hutchings | 69. Thundercat | 70. Flying Lotus | 71. BadBadNotGood | 72. Snarky Puppy | 73. Jacob Collier | 74. Cory Henry | 75. Vulfpeck | 76. Louis Jordan | 77. Cab Calloway | 78. Glenn Miller | 79. Benny Goodman | 80. Artie Shaw | 81. Fats Waller | 82. Jelly Roll Morton | 83. King Oliver | 84. Sidney Bechet | 85. Coleman Hawkins | 86. Lester Young | 87. Dexter Gordon | 88. Stan Kenton | 89. Maynard Ferguson | 90. Buddy Rich | 91. Gene Krupa | 92. Elvin Jones | 93. Art Blakey | 94. Max Roach | 95. Tony Williams | 96. Jack DeJohnette | 97. Ron Carter | 98. Jaco Pastorius | 99. Marcus Miller | 100. Victor Wooten.
""",
  'hipHopRapTrap':
      """
Tupac Shakur | 2. The Notorious B.I.G. | 3. Jay-Z | 4. Nas | 5. Eminem | 6. Dr. Dre | 7. Snoop Dogg | 8. Kendrick Lamar | 9. Kanye West | 10. Drake | 11. Rakim | 12. KRS-One | 13. Public Enemy | 14. Wu-Tang Clan | 15. Outkast | 16. N.W.A | 17. Run-D.M.C. | 18. Beastie Boys | 19. LL Cool J | 20. Ice Cube | 21. 50 Cent | 22. Lil Wayne | 23. J. Cole | 24. Future | 25. Travis Scott | 26. Young Thug | 27. Migos | 28. Gucci Mane | 29. T.I. | 30. Jeezy | 31. Rick Ross | 32. Nicki Minaj | 33. Cardi B | 34. Megan Thee Stallion | 35. Doja Cat | 36. Lauryn Hill | 37. Missy Elliott | 38. Queen Latifah | 39. Salt-N-Pepa | 40. Lil' Kim | 41. Foxy Brown | 42. Eve | 43. Trina | 44. Remy Ma | 45. A\$AP Rocky | 46. Tyler, The Creator | 47. Childish Gambino | 48. Mac Miller | 49. Logic | 50. Post Malone | 51. Juice WRLD | 52. XXXTentacion | 53. Pop Smoke | 54. 21 Savage | 55. Lil Baby | 56. Gunna | 57. Roddy Ricch | 58. DaBaby | 59. Jack Harlow | 60. Central Cee | 61. Stormzy | 62. Skepta | 63. Dave | 64. Burna Boy | 65. Wizkid | 66. Bad Bunny | 67. Anuel AA | 68. Myke Towers | 69. Eladio Carrión | 70. Bryant Myers | 71. Noriel | 72. De La Ghetto | 73. Arcángel | 74. Ñengo Flow | 75. Ozuna | 76. J Balvin | 77. Maluma | 78. Rauw Alejandro | 79. Feid | 80. Bizarrap | 81. Duki | 82. Trueno | 83. Paulo Londra | 84. C. Tangana | 85. Yung Beef | 86. Natanael Cano | 87. Peso Pluma | 88. Ghostface Killah | 89. Method Man | 90. Raekwon | 91. Redman | 92. Busta Rhymes | 93. Ludacris | 94. Nelly | 95. Ja Rule | 96. DMX | 97. The Game | 98. Common | 99. Mos Def | 100. Talib Kweli.
""",
  'electronicHouseTechno': """
Kraftwerk | 2. Daft Punk | 3. The Chemical Brothers | 4. The Prodigy | 5. Aphex Twin | 6. Jean-Michel Jarre | 7. Vangelis | 8. Giorgio Moroder | 9. Brian Eno | 10. Tangerine Dream | 11. Frankie Knuckles | 12. Marshall Jefferson | 13. Larry Heard | 14. Juan Atkins | 15. Derrick May | 16. Kevin Saunderson | 17. Carl Craig | 18. Richie Hawtin | 19. Jeff Mills | 20. Laurent Garnier | 21. Carl Cox | 22. Fatboy Slim | 23. Moby | 24. Underworld | 25. Orbital | 26. Massive Attack | 27. Portishead | 28. Tricky | 29. Burial | 30. Four Tet | 31. Floating Points | 32. Bonobo | 33. Nicolas Jaar | 34. Ricardo Villalobos | 35. Sven Väth | 36. Paul van Dyk | 37. Armin van Buuren | 38. Tiësto | 39. David Guetta | 40. Calvin Harris | 41. Avicii | 42. Swedish House Mafia | 43. Skrillex | 44. Deadmau5 | 45. Justice | 46. Disclosure | 47. Flume | 48. Kaytranada | 49. Peggy Gou | 50. Charlotte de Witte | 51. Amelie Lens | 52. Nina Kraviz | 53. Solomun | 54. Tale Of Us | 55. Maceo Plex | 56. Black Coffee | 57. Honey Dijon | 58. Kerri Chandler | 59. Masters At Work | 60. Todd Terry | 61. Pete Tong | 62. Danny Tenaglia | 63. Sasha | 64. John Digweed | 65. Hernán Cattáneo | 66. Eric Prydz | 67. Deadmau5 | 68. Zedd | 69. Martin Garrix | 70. Marshmello | 71. Kygo | 72. Alan Walker | 73. Fisher | 74. Dom Dolla | 75. Fred again.. | 76. Jamie xx | 77. Caribou | 78. Jon Hopkins | 79. Nils Frahm | 80. Ryuichi Sakamoto | 81. Yellow Magic Orchestra | 82. Art of Noise | 83. New Order | 84. Depeche Mode | 85. Pet Shop Boys | 86. Erasure | 87. Goldfrapp | 88. Röyksopp | 89. Boards of Canada | 90. Autechre | 91. Squarepusher | 92. Venetian Snares | 93. Pendulum | 94. Chase & Status | 95. Noisia | 96. Amon Tobin | 97. Tipper | 98. Pretty Lights | 99. Bassnectar | 100. G Jones.
""",
  'reggaeSkaPunk': """
Bob Marley | 2. Peter Tosh | 3. Bunny Wailer | 4. Jimmy Cliff | 5. Burning Spear | 6. Toots & The Maytals | 7. Desmond Dekker | 8. The Skatalites | 9. Lee "Scratch" Perry | 10. King Tubby | 11. Gregory Isaacs | 12. Dennis Brown | 13. Black Uhuru | 14. Steel Pulse | 15. Third World | 16. UB40 | 17. Alpha Blondy | 18. Lucky Dube | 19. Shaggy | 20. Sean Paul | 21. Damian Marley | 22. Stephen Marley | 23. Ziggy Marley | 24. Chronixx | 25. Koffee | 26. Protoje | 27. Buju Banton | 28. Beenie Man | 29. Sizzla | 30. Capleton | 31. Prince Buster | 32. Laurel Aitken | 33. Madness | 34. The Specials | 35. The Selecter | 36. Bad Manners | 37. The Beat | 38. Fishbone | 39. The Mighty Mighty Bosstones | 40. No Doubt | 41. Sublime | 42. Rancid | 43. Operation Ivy | 44. Reel Big Fish | 45. Less Than Jake | 46. Streetlight Manifesto | 47. Goldfinger | 48. Save Ferris | 49. Tokyo Ska Paradise Orchestra | 50. Ska-P | 51. Sex Pistols | 52. The Clash | 53. Ramones | 54. The Damned | 55. Buzzcocks | 56. Dead Kennedys | 57. Black Flag | 58. Bad Brains | 59. Minor Threat | 60. Fugazi | 61. Descendents | 62. Bad Religion | 63. NOFX | 64. Pennywise | 65. Millencolin | 66. Green Day | 67. The Offspring | 68. Blink-182 | 69. Sum 41 | 70. Rise Against | 71. Anti-Flag | 72. Propagandhi | 73. Refused | 74. At the Drive-In | 75. Fugazi | 76. Husker Du | 77. The Replacements | 78. Minutemen | 79. Social Distortion | 80. Stooges | 81. MC5 | 82. New York Dolls | 83. Richard Hell | 84. Television | 85. Patti Smith | 86. Siouxsie and the Banshees | 87. The Slits | 88. X-Ray Spex | 89. Crass | 90. Discharge | 91. G.B.H. | 92. Exploited | 93. Misfits | 94. Danzig | 95. Circle Jerks | 96. T.S.O.L. | 97. Agent Orange | 98. Adolescents | 99. Fear | 100. Suicidal Tendencies.
""",
  'metal': """
Black Sabbath | 2. Metallica | 3. Iron Maiden | 4. Judas Priest | 5. Slayer | 6. Megadeth | 7. Anthrax | 8. Pantera | 9. Motorhead | 10. Ozzy Osbourne | 11. Ronnie James Dio | 12. Deep Purple | 13. Led Zeppelin | 14. AC/DC | 15. Guns N' Roses | 16. Alice Cooper | 17. Kiss | 18. Van Halen | 19. Motley Crue | 20. Def Leppard | 21. Scorpions | 22. Helloween | 23. Blind Guardian | 24. Dream Theater | 25. Tool | 26. Mastodon | 27. Gojira | 28. Meshuggah | 29. Opeth | 30. Porcupine Tree | 31. System of a Down | 32. Slipknot | 33. Korn | 34. Deftones | 35. Linkin Park | 36. Avenged Sevenfold | 37. Disturbed | 38. Rammstein | 39. Sepultura | 40. Soulfly | 41. Lamb of God | 42. Killswitch Engage | 43. Trivium | 44. Bullet for My Valentine | 45. Bring Me the Horizon | 46. Architects | 47. Parkway Drive | 48. In Flames | 49. At the Gates | 50. Dark Tranquillity | 51. Children of Bodom | 52. Nightwish | 53. Within Temptation | 54. Epica | 55. Lacuna Coil | 56. Evanescence | 57. Arch Enemy | 58. Behemoth | 59. Mayhem | 60. Emperor | 61. Enslaved | 62. Immortal | 63. Dimmu Borgir | 64. Cradle of Filth | 65. Cannibal Corpse | 66. Death | 67. Morbid Angel | 68. Deicide | 69. Obituary | 70. Napalm Death | 71. Carcass | 72. At the Gates | 73. Entombed | 74. Bathory | 75. Venom | 76. Mercyful Fate | 77. King Diamond | 78. Celtic Frost | 79. Hellhammer | 80. Kreator | 81. Destruction | 82. Sodom | 83. Testament | 84. Exodus | 85. Overkill | 86. Machine Head | 87. Fear Factory | 88. Static-X | 89. Coal Chamber | 90. Mudvayne | 91. Five Finger Death Punch | 92. Ghost | 93. Volbeat | 94. Sabaton | 95. Powerwolf | 96. Amon Amarth | 97. Babymetal | 98. Polyphia | 99. Animals as Leaders | 100. Periphery.
""",
  'classical': """
Bach | 2. Mozart | 3. Beethoven | 4. Wagner | 5. Brahms | 6. Schubert | 7. Tchaikovsky | 8. Handel | 9. Chopin | 10. Liszt | 11. Haydn | 12. Vivaldi | 13. Debussy | 14. Ravel | 15. Stravinsky | 16. Mahler | 17. Verdi | 18. Puccini | 19. Rachmaninoff | 20. Mendelssohn | 21. Schumann | 22. Dvořák | 23. Strauss (Johann) | 24. Strauss (Richard) | 25. Sibelius | 26. Grieg | 27. Elgar | 28. Holst | 29. Vaughan Williams | 30. Britten | 31. Purcell | 32. Monteverdi | 33. Palestrina | 34. Josquin des Prez | 35. Byrd | 36. Tallis | 37. Corelli | 38. Scarlatti (Domenico) | 39. Couperin | 40. Rameau | 41. Lully | 42. Gluck | 43. Salieri | 44. Boccherini | 45. Clementi | 46. Hummel | 47. Czerny | 48. Paganini | 49. Berlioz | 50. Rossini | 51. Donizetti | 52. Bellini | 53. Bizet | 54. Saint-Saëns | 55. Fauré | 56. Massenet | 57. Gounod | 58. Offenbach | 59. Rimsky-Korsakov | 60. Mussorgsky | 61. Borodin | 62. Prokofiev | 63. Shostakovich | 64. Scriabin | 65. Bartók | 66. Kodály | 67. Janáček | 68. Smetana | 69. Albéniz | 70. Granados | 71. Falla | 72. Rodrigo | 73. Villa-Lobos | 74. Ginastera | 75. Piazzolla | 76. Gershwin | 77. Copland | 78. Barber | 79. Ives | 80. Bernstein | 81. Glass | 82. Reich | 83. Adams | 84. Pärt | 85. Górecki | 86. Penderecki | 87. Messiaen | 88. Boulez | 89. Stockhausen | 90. Xenakis | 91. Ligeti | 92. Takemitsu | 93. Tan Dun | 94. John Williams | 95. Hans Zimmer | 96. Ennio Morricone | 97. Ludovico Einaudi | 98. Max Richter | 99. Jóhann Jóhannsson | 100. Hildur Guðnadóttir.
""",
  'flamencoFolklore': """
Camarón de la Isla | 2. Paco de Lucía | 3. Enrique Morente | 4. Lola Flores | 5. Manolo Caracol | 6. Niña de los Peines | 7. Carmen Amaya | 8. Sabicas | 9. Tomatito | 10. Vicente Amigo | 11. Diego el Cigala | 12. Estrella Morente | 13. Miguel Poveda | 14. José Mercé | 15. Rocío Jurado | 16. Bambino | 17. Chano Lobato | 18. Pericón de Cádiz | 19. Antonio Mairena | 20. Terremoto de Jerez | 21. Agujetas | 22. Chocolate | 23. Fernanda de Utrera | 24. Bernarda de Utrera | 25. La Paquera de Jerez | 26. Manuela Carrasco | 27. Farruquito | 28. Sara Baras | 29. Antonio Canales | 30. Joaquín Cortés | 31. Niña Pastori | 32. Marina Heredia | 33. Arcángel | 34. Pitingo | 35. Rosario Flores | 36. Antonio Flores | 37. Kiko Veneno | 38. Raimundo Amador | 39. Ketama | 40. Navajita Plateá | 41. O'funk'illo | 42. Chambao | 43. Gipsy Kings | 44. Azúcar Moreno | 45. Los Chunguitos | 46. Los Chichos | 47. El Fary | 48. Manolo Escobar | 49. Antonio Molina | 50. Juanito Valderrama | 51. Mercedes Sosa | 52. Atahualpa Yupanqui | 53. Violeta Parra | 54. Víctor Jara | 55. Chavela Vargas | 56. Amparo Ochoa | 57. Facundo Cabral | 58. Alberto Cortez | 59. Joan Manuel Serrat | 60. Joaquín Sabina | 61. Luis Eduardo Aute | 62. Silvio Rodríguez | 63. Pablo Milanés | 64. Jorge Drexler | 65. Natalia Lafourcade | 66. Lila Downs | 67. Soledad Pastorutti | 68. Los Chalchaleros | 69. Los Fronterizos | 70. Horacio Guarany | 71. Peteco Carabajal | 72. Illapu | 73. Inti-Illimani | 74. Quilapayún | 75. Los Kjarkas | 76. Savia Andina | 77. Eva Ayllón | 78. Susana Baca | 79. Chabuca Granda | 80. Totó la Momposina | 81. Joe Arroyo | 82. Carlos Vives | 83. Juan Luis Guerra | 84. Ruben Blades | 85. Simón Díaz | 86. Soledad Bravo | 87. Gualberto Ibarreto | 88. Cecilia Todd | 89. Los Olimareños | 90. Alfredo Zitarrosa | 91. Daniel Viglietti | 92. José Larralde | 93. Argentino Luna | 94. Jorge Cafrune | 95. Tarragó Ros | 96. Antonio Tarragó Ros | 97. Teresa Parodi | 98. Ramona Galarza | 99. Chango Spasiuk | 100. Lisandro Aristimuño.
""",
  'latinSalsaBachataReggaeton': """
Celia Cruz | 2. Héctor Lavoe | 3. Rubén Blades | 4. Willie Colón | 5. Juan Luis Guerra | 6. Marc Anthony | 7. Romeo Santos | 8. Daddy Yankee | 9. Don Omar | 10. Bad Bunny | 11. J Balvin | 12. Karol G | 13. Luis Miguel | 14. Selena | 15. Gloria Estefan | 16. Shakira | 17. Ricky Martin | 18. Jennifer Lopez | 19. Pitbull | 20. Maluma | 21. Ozuna | 22. Rauw Alejandro | 23. Anuel AA | 24. Wisin & Yandel | 25. Tego Calderón | 26. Ivy Queen | 27. Arcángel | 28. De La Ghetto | 29. Zion & Lennox | 30. Ñengo Flow | 31. Tito El Bambino | 32. Nicky Jam | 33. Farruko | 34. Sebastián Yatra | 35. Camilo | 36. Christian Nodal | 37. Alejandro Fernández | 38. Vicente Fernández | 39. Juan Gabriel | 40. Marco Antonio Solís | 41. Roberto Carlos | 42. Julio Iglesias | 43. Raphael | 44. Camilo Sesto | 45. José José | 46. Luis Fonsi | 47. Chayanne | 48. Ricardo Arjona | 49. Maná | 50. Soda Stereo | 51. Gustavo Cerati | 52. Enanitos Verdes | 53. Hombres G | 54. Miguel Bosé | 55. Alejandro Sanz | 56. Laura Pausini | 57. Eros Ramazzotti | 58. Thalía | 59. Paulina Rubio | 60. Belinda | 61. Becky G | 62. Anitta | 63. Natti Natasha | 64. Rosalia | 65. C. Tangana | 66. Quevedo | 67. Bizarrap | 68. Duki | 69. Tini | 70. Lali | 71. Prince Royce | 72. Anthony Santos | 73. Frank Reyes | 74. Zacarías Ferreira | 75. Luis Vargas | 76. Raulin Rodriguez | 77. El Torito | 78. Aventura | 79. Monchy & Alexandra | 80. Oscar D'León | 81. Gilberto Santa Rosa | 82. Victor Manuelle | 83. Eddie Palmieri | 84. Ray Barretto | 85. Ismael Rivera | 86. Cheo Feliciano | 87. Benny Moré | 88. Tito Puente | 89. Fania All-Stars | 90. Buena Vista Social Club | 91. Ibrahim Ferrer | 92. Omara Portuondo | 93. Compay Segundo | 94. Pablo Milanés | 95. Silvio Rodríguez | 96. Mercedes Sosa | 97. Carlos Gardel | 98. Astor Piazzolla | 99. Jorge Drexler | 100. Natalia Lafourcade.
""",
  'country': """
Johnny Cash | 2. Dolly Parton | 3. Willie Nelson | 4. Hank Williams | 5. George Strait | 6. Garth Brooks | 7. Loretta Lynn | 8. Patsy Cline | 9. Merle Haggard | 10. Waylon Jennings | 11. Kenny Rogers | 12. Reba McEntire | 13. Alan Jackson | 14. Shania Twain | 15. Taylor Swift | 16. Carrie Underwood | 17. Tim McGraw | 18. Faith Hill | 19. George Jones | 20. Tammy Wynette | 21. Conway Twitty | 22. Glen Campbell | 23. Charley Pride | 24. Kris Kristofferson | 25. Emmylou Harris | 26. Linda Ronstadt | 27. June Carter Cash | 28. Jimmie Rodgers | 29. The Carter Family | 30. Bob Wills | 31. Bill Monroe | 32. Flatt & Scruggs | 33. Earl Scruggs | 34. Chet Atkins | 35. Marty Robbins | 36. Jim Reeves | 37. Don Williams | 38. Ronnie Milsap | 39. Barbara Mandrell | 40. Crystal Gayle | 41. Oak Ridge Boys | 42. Statler Brothers | 43. Alabama | 44. Brooks & Dunn | 45. Sugarland | 46. Lady A | 47. Little Big Town | 48. Zac Brown Band | 49. Luke Combs | 50. Morgan Wallen | 51. Chris Stapleton | 52. Miranda Lambert | 53. Blake Shelton | 54. Keith Urban | 55. Brad Paisley | 56. Jason Aldean | 57. Eric Church | 58. Dierks Bentley | 59. Kacey Musgraves | 60. Maren Morris | 61. Tyler Childers | 62. Sturgill Simpson | 63. Colter Wall | 64. Billy Strings | 65. Alison Krauss | 66. Vince Gill | 67. Dwight Yoakam | 68. Steve Earle | 69. Townes Van Zandt | 70. Guy Clark | 71. Lucinda Williams | 72. John Prine | 73. Emmylou Harris | 74. Gram Parsons | 75. Flying Burrito Brothers | 76. The Byrds | 77. Nitty Gritty Dirt Band | 78. Old Crow Medicine Show | 79. Mumford & Sons | 80. Lumineers | 81. Sheryl Crow | 82. Kid Rock | 83. Darius Rucker | 84. Kane Brown | 85. Thomas Rhett | 86. Sam Hunt | 87. Florida Georgia Line | 88. Dan + Shay | 89. Rascal Flatts | 90. Lonestar | 91. Diamond Rio | 92. Clint Black | 93. Travis Tritt | 94. Mary Chapin Carpenter | 95. Trisha Yearwood | 96. Wynonna Judd | 97. The Judds | 98. Dixie Chicks (The Chicks) | 99. LeAnn Rimes | 100. Tanya Tucker.
""",
};

const Map<String, String> _styleToBucket = {
  'Rock': 'rock',
  'Pop': 'pop',
  'Indie': 'indie',
  'Funk': 'funkSoulRb',
  'Soul': 'funkSoulRb',
  'R&B': 'funkSoulRb',
  'Jazz': 'jazzBlues',
  'Blues': 'jazzBlues',
  'Hip-Hop': 'hipHopRapTrap',
  'Rap': 'hipHopRapTrap',
  'Trap': 'hipHopRapTrap',
  'Electrónica': 'electronicHouseTechno',
  'House': 'electronicHouseTechno',
  'Techno': 'electronicHouseTechno',
  'Reggae': 'reggaeSkaPunk',
  'Ska': 'reggaeSkaPunk',
  'Punk': 'reggaeSkaPunk',
  'Metal': 'metal',
  'Clásica': 'classical',
  'Flamenco': 'flamencoFolklore',
  'Folklore': 'flamencoFolklore',
  'Latino': 'latinSalsaBachataReggaeton',
  'Salsa': 'latinSalsaBachataReggaeton',
  'Bachata': 'latinSalsaBachataReggaeton',
  'Reggaetón': 'latinSalsaBachataReggaeton',
  'Country': 'country',
};

final Map<String, List<String>> _parsedBucketCache = {};

List<String> affinityArtistOptionsForStyle(String? style) {
  if (style == null) {
    return const [];
  }

  final bucket = _styleToBucket[style.trim()];
  if (bucket == null) {
    return const [];
  }

  return _parsedBucketCache.putIfAbsent(bucket, () {
    final raw = _bucketArtistsRaw[bucket] ?? '';
    return List.unmodifiable(_parseArtists(raw));
  });
}

List<String> _parseArtists(String raw) {
  final parsed = <String>[];
  final seen = <String>{};

  for (final token in raw.split('|')) {
    var artist = token.trim();
    if (artist.isEmpty) {
      continue;
    }

    artist = artist.replaceFirst(RegExp(r'^\d+\.\s*'), '').trim();
    artist = artist.replaceFirst(RegExp(r'^[•·-]\s*'), '').trim();
    if (artist.endsWith('.')) {
      artist = artist.substring(0, artist.length - 1).trim();
    }

    if (artist.isEmpty) {
      continue;
    }

    final key = artist.toLowerCase();
    if (seen.add(key)) {
      parsed.add(artist);
    }
  }

  return parsed;
}
