const List<String> spanishProvinces = [
  'A Coruña',
  'Álava',
  'Albacete',
  'Alicante',
  'Almería',
  'Asturias',
  'Ávila',
  'Badajoz',
  'Barcelona',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Cantabria',
  'Castellón',
  'Ciudad Real',
  'Córdoba',
  'Cuenca',
  'Girona',
  'Granada',
  'Guadalajara',
  'Gipuzkoa',
  'Huelva',
  'Huesca',
  'Illes Balears',
  'Jaén',
  'León',
  'Lleida',
  'Lugo',
  'Madrid',
  'Málaga',
  'Murcia',
  'Navarra',
  'Ourense',
  'Palencia',
  'Las Palmas',
  'Pontevedra',
  'La Rioja',
  'Salamanca',
  'Santa Cruz de Tenerife',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Teruel',
  'Toledo',
  'Valencia',
  'Valladolid',
  'Bizkaia',
  'Zamora',
  'Zaragoza',
];

const Map<String, List<String>> spanishCitiesByProvince = {
  'A Coruña': ['A Coruña'],
  'Álava': ['Vitoria-Gasteiz'],
  'Albacete': ['Albacete'],
  'Alicante': ['Alicante'],
  'Almería': ['Almería'],
  'Asturias': ['Oviedo'],
  'Ávila': ['Ávila'],
  'Badajoz': ['Badajoz'],
  'Barcelona': ['Barcelona'],
  'Burgos': ['Burgos'],
  'Cáceres': ['Cáceres'],
  'Cádiz': ['Cádiz'],
  'Cantabria': ['Santander'],
  'Castellón': ['Castellón de la Plana'],
  'Ciudad Real': ['Ciudad Real'],
  'Córdoba': ['Córdoba'],
  'Cuenca': ['Cuenca'],
  'Girona': ['Girona'],
  'Granada': ['Granada'],
  'Guadalajara': ['Guadalajara'],
  'Gipuzkoa': ['San Sebastián'],
  'Huelva': ['Huelva'],
  'Huesca': ['Huesca'],
  'Illes Balears': ['Palma'],
  'Jaén': ['Jaén'],
  'León': ['León'],
  'Lleida': ['Lleida'],
  'Lugo': ['Lugo'],
  'Madrid': ['Madrid'],
  'Málaga': ['Málaga'],
  'Murcia': ['Murcia'],
  'Navarra': ['Pamplona'],
  'Ourense': ['Ourense'],
  'Palencia': ['Palencia'],
  'Las Palmas': ['Las Palmas de Gran Canaria'],
  'Pontevedra': ['Pontevedra'],
  'La Rioja': ['Logroño'],
  'Salamanca': ['Salamanca'],
  'Santa Cruz de Tenerife': ['Santa Cruz de Tenerife'],
  'Segovia': ['Segovia'],
  'Sevilla': ['Sevilla'],
  'Soria': ['Soria'],
  'Tarragona': ['Tarragona'],
  'Teruel': ['Teruel'],
  'Toledo': ['Toledo'],
  'Valencia': ['Valencia'],
  'Valladolid': ['Valladolid'],
  'Bizkaia': ['Bilbao'],
  'Zamora': ['Zamora'],
  'Zaragoza': ['Zaragoza'],
};
